### PR TITLE
Pandoc syntax highlighting

### PR DESCRIPTION
**Pull request by Joe7M**
Hi Chris,

when building the website pandoc will create syntax highlighting now. This was quite easy to implement, because pandoc supports KDE syntax-highlighting definitions. The only thing I needed to do was to provide the Kate syntax-highlighting file, I created a while ago. For every code-block in the markdown files a "smallbasic" tag has to be added. For testing I did this for some files. I added the necessary style-sheets for syntax highlighting to the css/style.css file.  I tested the html-files with the simple python http server. I hope that in the real world it will work, too. 
Next step would be to add the smallbasic-tag to all markdown files. Maybe there is a smart way using console commands in Linux.

Best regards, Joerg

### CODE REVIEW

**Review by chrisws — APPROVED** [review]
This looks great. 

I think a better way to handle adding the smallbasic label to the start of the triple backticks would be to add a new step in Makefile - this would be another SmallBASIC program to read the .markdown file to insert the tag, make would store the result in a new temporary location and then use that for the existing step.  I'll merge this for now, but try to play around with this idea to see how it goes.

**Comment by chrisws** [comment]
Adding the extra step to the Makefile was pretty simple. It now preprocesses the markdown files to add the "smallbasic" tag to the opening tripple back-tick blocks.

There are a few problems though:

1. The rules xml file doesn't like comments.

[WARNING] Could not highlight code block:
IncludeRules in smallbasic requires undefined context ##Comments

2. The clipboard copy button now needs to exclude HTML markup

3. The IDE reference files (shown in the FLTK version) need to avoid the fancy markup

I can fix 2+3.

Cheers,
Chris

**Comment by Joe7M** [comment]
See new pull request.

The line `<IncludeRules context="##Comments" />` in the xml file links to another file called Comments.xml. Most probably you are not using KDE and therefore this file is missing and creating the error. I removed that line, because the additional rules are not relevant for SB. I can't test if the error is resolved. On my KDE sytem Kate and pandoc are fine with the new xml file. I hope it will work now on your system. If not, let me know what Linux you are using and I can setup a virtual machine.

Best regards, Joerg

**Comment by chrisws** [comment]
I've pushed all the changes. Hopefully nothing broken.

I reverted your changes to the reference markdown's to remove the smallbasic tag after the backticks.

This allows the IDE/FLTK version of the reference to remain as before. These are rendered in a very primitive html rendering widget so can't deal with anything too fancy.

The mkhl.bas program adds the smallbasic tag back to an intermediate version of the markdown during the build process.

Thanks so much for your excellent idea of adding syntax highlighting. Its looks fantastic !

Cheers,
Chris

**Comment by Joe7M** [comment]
The websites looking great with the syntax highlighting. I also have to thank you.

**Pull request merged**
