### PR TITLE
New articles for the plugins clipboard and gifenc

### PR DESCRIPTION
**Pull request by Joe7M**

### CODE REVIEW

**Comment by chrisws** [comment]
Cool stuff - only could you please rename .md files to .markdown? 

This is the extension used in the site Makefile. see https://github.com/smallbasic/smallbasic.github.io/blob/master/_build/Makefile

**Comment by Joe7M** [comment]
sorry my fault. I have renamed the files.

**Comment by chrisws** [comment]
Thanks so much for this!

The raylib article looks great but it's missing a few things:
- there's no link from the articles page.
- all the images from Shapes section to the end of the page are missing.

**Comment by Joe7M** [comment]
Hi Chris, the raylib article was not meant to be published. I usually edit the markdown files in the browser and at the end of the day I save them (commit). What I forgot was, that a commit is automatically added to an open pull request. Because of this, there is now an unfinished file. I'll correct it the next days and will start a new pull request. Sorry for this. It seems I'm still a beginner ;)

**Pull request merged**
